### ISSUE TITLE
Offline Betrieb des Servers

### ISSUE THREAD

**Issue by heintzl** [eichtal/kernbeisser#15]
Beim Testen von WooCommerce im Zug (=kaum Internet...) fällt auf: Jeder Seitenaufbau wartet auf externe Ressourcen (css und images), u.a. fonts.googleapis.com, 2.gravatar.com etc. Das kann den offlinebetrieb natürlich stark beeinträchtigen...
![grafik](https://cloud.githubusercontent.com/assets/25566469/22628198/1cb21f0e-ebd0-11e6-928e-2f74f10fb0d0.png)

**Comment by eichtal** [comment]
Ja, guter Punkt. Das müssen wir auf jeden Fall prüfen. Gravatar können wir vernachlässigen, das ist ein Service, der Nutzerkonten bereitstellt, die dann übergreifend über mehrere Wordpress-Installationen gelten. Da wir nur lokale Nutzerkonten verwenden, spielt das keine Rolle. jQuery-Dateien und Fonts müssen wir lokal bereit stellen. Entweder müssen wir hierfür in den Quelldateien die externen Aufrufe durch lokale Ressourcen ersetzen oder in einen Cache laden, bevor der Server offline gestellt wird.

**Comment by heintzl** [comment]
Quelldateien modifizieren halte ich für ungünstig, da es bei jedem Update wiederholt werden muss. Ich vermute, ein Proxy würde es auch tun, werde mir das bei Gelegenheit mal anschauen.

**Comment by heintzl** [comment]
Falls wir kostenpflichtige Module benötigen, muss geklärt werden, wie die Aktivierung erfolgt. Falls sie regelmäßig über home calls verifiziert wird, machen wir dicke Backen :(

**Comment by eichtal** [comment]
Üblicherweise hinterlegt man in Wordpress einen Lizenzschlüssel, der dann initial überprüft wird. Ggf. passiert das natürlich auch öfter.

**Comment by heintzl** [comment]
Ich habe heute versucht, Probleme beim Aufbau der Seiten mit fehlender Internet-Verbindung zu reproduzieren - erfolglos :-)
Vielleicht liegt es daran, dass ich wordpress und woocommerce aktualisiert habe, oder dass ich nicht alle plugins installiert habe, die ich im Februar hatte, oder die VM ist jetzt anders eingerichtet, oder, oder...
Ich schlage vor, dass Issue zu schließen und als Testfall vorzusehen. Wenn feststeht, wie wir eine Instanz im Kernbeisser-Laden deployen, muss Zeit eingeplant werden, um ggf. Offline-Issues zu behandeln.
